### ISSUE TITLE
Letras erradas não estão armazenadas em nenhum lugar

### ISSUE THREAD

**Issue by lucasgris** [lucasgris/jogo-forca#1]
Está faltando mostrar as letras que o jogador erra durante um jogo.

- [x] Criar um requisito para mostrar as letras que o jogador errou.
- [ ] Adicionar lista na classe correspondente.

**Comment by Pextre** [comment]
Cara , se for fazer um teclado para o jogador ir clicando , é só fazer elas desaparecerem independente se acertou ou não. Assim fica mais fácil na minha opinião

**Comment by lucasgris** [comment]
Hum, verdade. Fica até melhor.

Eu esqueci de fazer o teclado na verdade.
Mas mesmo assim preciso adicionar isso aos requisitos.
